In [1]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\dalcaraz.ferri\.virtualenvs\sw_vs_avengers-zvndk4ih\lib\site-packages (3.0.9)
Requirement already satisfied: et-xmlfile in c:\users\dalcaraz.ferri\.virtualenvs\sw_vs_avengers-zvndk4ih\lib\site-packages (from openpyxl) (1.1.0)

## IMPORTAR LIBRERÍAS

In [2]:
import pandas as pd

### Cargar datos

In [3]:
raw_data = pd.read_excel('Recaudaciones.xlsx')
raw_data

,PELICULA,PRESUPUESTO,RECAUDACION (millones de dolares),ESTRENO
0,Star Wars : Episodio IV - Una nueva esperanza,"11,000,000",775.398007,1977
1,Star Wars: Episodio V - EL imperio contraataca,"18,000,000",538.375067,1980
2,Star Wars : Episodio VI - El retorno del Jedi,"32,500,000",475.106177,1983
3,Star Wars: Episodio I - La Amenaza fantasma,"115,000,000",1027.082707,1999
4,Star Wars: Episodio II - El ataque de los clones,"115,000,000",653.779970,2002
5,Star Wars: Episodio III - La venganza de los Sith,"113,000,000",868.390560,2005
6,The Avengers,"220,000,000",15188.115515,2012
7,Star Wars : Episodio VII - El despertar de la...,"245,000,000",2069.521700,2015
8,The Avengers: Age of Ultron,"250,000,000",1402.809540,2015
9,Star Wars : Episodio VIII - Los últimos Jedi,"317,000,000",1332.698830,2017
10,The Avengers: Infinity War,"316,000,000",2048.359754,2018
11,Star Wars: Episodio IX -El ascenso de Skywalker,"275,000,000",1078.232589,2019
12,The Avengers: Endgame,"356,000,000",2797.501328,2019

## Descripcion de la base de datos

La tabla muestra los presupuestos de las películas correspondientes a las sagas de Star Wars y de Avengers. Se tienen en cuenta las recaudaciones a nivel mundial sin añadir o contabilizar los preestrenos o estrenos "en casa". La moneda usada es el Dólar Estadounidense
fuente https://www.boxofficemojo.com/

Al mirar la tabla de datos podemos observar varias cosas: La primera es que las columnas de PRESUPUESTO Y RECAUDACIÓN están en unidades diferentes: mientras que el presupuesto se indica en unidades absolutas, la recaudación está en millones de dólares, por lo que habrá que tenerlo todo en las mismas unidades.Lo segundo es que podemos ver que los años de estreno y por tanto recaudación son distintos, así que para realizar comparaciones habrá que ponderar las cantidades segúon la inflación actual (a última fecha disponible).
Se observa además lo que podría ser una dificultad añadida, y es que  en algunos títulos hay un especio entre la palabra "Wars" y ":" y en otros no. Deberemos tenerlo en cuenta si necesitamos hacer un split para una posterior clasificación de dichas películas.

Para este análisis de datos se consideran las recaudaciones de las peliculas en su estreno mundial, así como la ponderacion por inflacion a Enero de 2022

#### Limpieza de datos

De forma preventiva, voy a eliminar espacios en blanco en los nombres de las columnas

In [4]:
raw_data.columns=[column.strip() for column in raw_data.columns]

No me convence que el año de estreno esté al final, voy a ponerlo justo después del título de la película.

In [5]:
raw_data=raw_data[['PELICULA', 'ESTRENO', 'PRESUPUESTO', 'RECAUDACION (millones de dolares)']]

### AJUSTE DE LAS UNIDADES DE LA COLUMNA PRESUPUESTO

Para realizar este ajuste, dividiré la columna entre 1.000.000 para establecerlo como "millones de dólares"

In [6]:
raw_data.describe()

           ESTRENO  RECAUDACION (millones de dolares)
count    13.000000                          13.000000
mean   2004.692308                        2327.336288
std      15.520871                        3924.590541
min    1977.000000                         475.106177
25%    1999.000000                         775.398007
50%    2012.000000                        1078.232589
75%    2017.000000                        2048.359754
max    2019.000000                       15188.115515

Observamos que ni la columna PELICULA ni la columna RECAUDACIÓN aparecen en el describe, me hace sospechar que RECAUDACION no es tipo numérico y es algo que habría que solucionar primero

In [7]:
raw_data.dtypes

PELICULA                              object
ESTRENO                                int64
PRESUPUESTO                           object
RECAUDACION (millones de dolares)    float64
dtype: object

Efectivamente, comprobamos que ni PELICULA ni PRESUPUESTO son columnas numéricas. El primer paso será entonces cambiar el tipo de dato de la columna PRESUPUESTO. aplicamos una función lambda para cambiar el tipo de dato y además aplicar este cambio de unidades.

In [8]:
raw_data

,PELICULA,ESTRENO,PRESUPUESTO,RECAUDACION (millones de dolares)
0,Star Wars : Episodio IV - Una nueva esperanza,1977,"11,000,000",775.398007
1,Star Wars: Episodio V - EL imperio contraataca,1980,"18,000,000",538.375067
2,Star Wars : Episodio VI - El retorno del Jedi,1983,"32,500,000",475.106177
3,Star Wars: Episodio I - La Amenaza fantasma,1999,"115,000,000",1027.082707
4,Star Wars: Episodio II - El ataque de los clones,2002,"115,000,000",653.779970
5,Star Wars: Episodio III - La venganza de los Sith,2005,"113,000,000",868.390560
6,The Avengers,2012,"220,000,000",15188.115515
7,Star Wars : Episodio VII - El despertar de la...,2015,"245,000,000",2069.521700
8,The Avengers: Age of Ultron,2015,"250,000,000",1402.809540
9,Star Wars : Episodio VIII - Los últimos Jedi,2017,"317,000,000",1332.698830
10,The Avengers: Infinity War,2018,"316,000,000",2048.359754
11,Star Wars: Episodio IX -El ascenso de Skywalker,2019,"275,000,000",1078.232589
12,The Avengers: Endgame,2019,"356,000,000",2797.501328

In [9]:
raw_data.insert(3,'PRESUPUESTO (millones de dólares)', raw_data['PRESUPUESTO'].apply(lambda x: float(x.replace(',',''))/1000000))

In [10]:
raw_data

,PELICULA,ESTRENO,PRESUPUESTO,PRESUPUESTO (millones de dólares),RECAUDACION (millones de dolares)
0,Star Wars : Episodio IV - Una nueva esperanza,1977,"11,000,000",11.0,775.398007
1,Star Wars: Episodio V - EL imperio contraataca,1980,"18,000,000",18.0,538.375067
2,Star Wars : Episodio VI - El retorno del Jedi,1983,"32,500,000",32.5,475.106177
3,Star Wars: Episodio I - La Amenaza fantasma,1999,"115,000,000",115.0,1027.082707
4,Star Wars: Episodio II - El ataque de los clones,2002,"115,000,000",115.0,653.779970
5,Star Wars: Episodio III - La venganza de los Sith,2005,"113,000,000",113.0,868.390560
6,The Avengers,2012,"220,000,000",220.0,15188.115515
7,Star Wars : Episodio VII - El despertar de la...,2015,"245,000,000",245.0,2069.521700
8,The Avengers: Age of Ultron,2015,"250,000,000",250.0,1402.809540
9,Star Wars : Episodio VIII - Los últimos Jedi,2017,"317,000,000",317.0,1332.698830
10,The Avengers: Infinity War,2018,"316,000,000",316.0,2048.359754
11,Star Wars: Episodio IX -El ascenso de Skywalker,2019,"275,000,000",275.0,1078.232589
12,The Avengers: Endgame,2019,"356,000,000",356.0,2797.501328

### PONDERACION DE MONEDAS POR INFLACION

Para el siguiente punto deberé de realizar una investigación y averiguar cuál es el último dato de inflación disponible a fecha 15.02.2022

la última cifra de la inflación disponible para EEUU (que usa el dólar) es del 7'5% (Enero de 2022)

In [11]:
inflacion = 7.5/100

In [12]:
raw_data.columns

Index(['PELICULA', 'ESTRENO', 'PRESUPUESTO',
       'PRESUPUESTO (millones de dólares)',
       'RECAUDACION (millones de dolares)'],
      dtype='object')

In [13]:
raw_data

,PELICULA,ESTRENO,PRESUPUESTO,PRESUPUESTO (millones de dólares),RECAUDACION (millones de dolares)
0,Star Wars : Episodio IV - Una nueva esperanza,1977,"11,000,000",11.0,775.398007
1,Star Wars: Episodio V - EL imperio contraataca,1980,"18,000,000",18.0,538.375067
2,Star Wars : Episodio VI - El retorno del Jedi,1983,"32,500,000",32.5,475.106177
3,Star Wars: Episodio I - La Amenaza fantasma,1999,"115,000,000",115.0,1027.082707
4,Star Wars: Episodio II - El ataque de los clones,2002,"115,000,000",115.0,653.779970
5,Star Wars: Episodio III - La venganza de los Sith,2005,"113,000,000",113.0,868.390560
6,The Avengers,2012,"220,000,000",220.0,15188.115515
7,Star Wars : Episodio VII - El despertar de la...,2015,"245,000,000",245.0,2069.521700
8,The Avengers: Age of Ultron,2015,"250,000,000",250.0,1402.809540
9,Star Wars : Episodio VIII - Los últimos Jedi,2017,"317,000,000",317.0,1332.698830
10,The Avengers: Infinity War,2018,"316,000,000",316.0,2048.359754
11,Star Wars: Episodio IX -El ascenso de Skywalker,2019,"275,000,000",275.0,1078.232589
12,The Avengers: Endgame,2019,"356,000,000",356.0,2797.501328

Para ponderar tanto el presupuesto como la recaudación, calculamos el 7'5% de cada cantidad y se lo restamos al total.

In [14]:
raw_data.insert(4,'PRESUPUESTO PONDERADO POR INFLACION',raw_data['PRESUPUESTO (millones de dólares)'].apply(lambda x: x-x*inflacion))
raw_data

,PELICULA,ESTRENO,PRESUPUESTO,PRESUPUESTO (millones de dólares),PRESUPUESTO PONDERADO POR INFLACION,RECAUDACION (millones de dolares)
0,Star Wars : Episodio IV - Una nueva esperanza,1977,"11,000,000",11.0,10.1750,775.398007
1,Star Wars: Episodio V - EL imperio contraataca,1980,"18,000,000",18.0,16.6500,538.375067
2,Star Wars : Episodio VI - El retorno del Jedi,1983,"32,500,000",32.5,30.0625,475.106177
3,Star Wars: Episodio I - La Amenaza fantasma,1999,"115,000,000",115.0,106.3750,1027.082707
4,Star Wars: Episodio II - El ataque de los clones,2002,"115,000,000",115.0,106.3750,653.779970
5,Star Wars: Episodio III - La venganza de los Sith,2005,"113,000,000",113.0,104.5250,868.390560
6,The Avengers,2012,"220,000,000",220.0,203.5000,15188.115515
7,Star Wars : Episodio VII - El despertar de la...,2015,"245,000,000",245.0,226.6250,2069.521700
8,The Avengers: Age of Ultron,2015,"250,000,000",250.0,231.2500,1402.809540
9,Star Wars : Episodio VIII - Los últimos Jedi,2017,"317,000,000",317.0,293.2250,1332.698830
10,The Avengers: Infinity War,2018,"316,000,000",316.0,292.3000,2048.359754
11,Star Wars: Episodio IX -El ascenso de Skywalker,2019,"275,000,000",275.0,254.3750,1078.232589
12,The Avengers: Endgame,2019,"356,000,000",356.0,329.3000,2797.501328

Hacemos la operación homónima para las recaudaciones:

In [15]:
raw_data.insert(6,'RECAUDACION PONDERADA POR INFLACION', raw_data['RECAUDACION (millones de dolares)'].apply(lambda x: x-x*inflacion))
raw_data

,PELICULA,ESTRENO,PRESUPUESTO,PRESUPUESTO (millones de dólares),PRESUPUESTO PONDERADO POR INFLACION,RECAUDACION (millones de dolares),RECAUDACION PONDERADA POR INFLACION
0,Star Wars : Episodio IV - Una nueva esperanza,1977,"11,000,000",11.0,10.1750,775.398007,717.243156
1,Star Wars: Episodio V - EL imperio contraataca,1980,"18,000,000",18.0,16.6500,538.375067,497.996937
2,Star Wars : Episodio VI - El retorno del Jedi,1983,"32,500,000",32.5,30.0625,475.106177,439.473214
3,Star Wars: Episodio I - La Amenaza fantasma,1999,"115,000,000",115.0,106.3750,1027.082707,950.051504
4,Star Wars: Episodio II - El ataque de los clones,2002,"115,000,000",115.0,106.3750,653.779970,604.746472
5,Star Wars: Episodio III - La venganza de los Sith,2005,"113,000,000",113.0,104.5250,868.390560,803.261268
6,The Avengers,2012,"220,000,000",220.0,203.5000,15188.115515,14049.006851
7,Star Wars : Episodio VII - El despertar de la...,2015,"245,000,000",245.0,226.6250,2069.521700,1914.307572
8,The Avengers: Age of Ultron,2015,"250,000,000",250.0,231.2500,1402.809540,1297.598824
9,Star Wars : Episodio VIII - Los últimos Jedi,2017,"317,000,000",317.0,293.2250,1332.698830,1232.746418
10,The Avengers: Infinity War,2018,"316,000,000",316.0,292.3000,2048.359754,1894.732772
11,Star Wars: Episodio IX -El ascenso de Skywalker,2019,"275,000,000",275.0,254.3750,1078.232589,997.365145
12,The Avengers: Endgame,2019,"356,000,000",356.0,329.3000,2797.501328,2587.688728

Nota: habiendo consultado varias fuentes de datos, he visto que los datos con respecto al presupuesto y la recaudación son los mismo, pero no he encontrado definición alguna sobre lo que se muestra con estas cantidades, lo que me hace preguntarme si la recaudación tiene en cuenta el presupuesto, es decir, está calculada como beneficio neto(recaudación menos presupuesto), o si bien es la recaudación en bruto(sin tener en cuenta el prespuesto de la película). La intuición me dice que es recaudación en bruto, lo cual lo tendré en cuenta en objetivos posteriores.

#### Categorización de los datos

Para facilitar el análisis de datos, voy a crear dos categorías dependiendo de si la película pertenece a la saga de Star Wars, o a la saga de Avengers

In [16]:
for i in raw_data['PELICULA']:
    print('Star' in i.split())

True
True
True
True
True
True
False
True
False
True
False
True
False

In [17]:
def seek_word(my_string,word):
    splited_string=my_string.split()
    result=None
    for i in splited_string:
        result=word in splited_string
    return result

In [18]:
def cat_film(string):
    word='Star'
    if seek_word(string,word):
        category = 'STAR WARS'
    else:
        category = 'AVENGERS'
    return category

In [19]:
raw_data['SAGA']=raw_data['PELICULA'].apply(lambda x: cat_film(x))
raw_data

C:\Users\dalcaraz.ferri\AppData\Local\Temp\ipykernel_26104\1931108493.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_data['SAGA']=raw_data['PELICULA'].apply(lambda x: cat_film(x))

,PELICULA,ESTRENO,PRESUPUESTO,PRESUPUESTO (millones de dólares),PRESUPUESTO PONDERADO POR INFLACION,RECAUDACION (millones de dolares),RECAUDACION PONDERADA POR INFLACION,SAGA
0,Star Wars : Episodio IV - Una nueva esperanza,1977,"11,000,000",11.0,10.1750,775.398007,717.243156,STAR WARS
1,Star Wars: Episodio V - EL imperio contraataca,1980,"18,000,000",18.0,16.6500,538.375067,497.996937,STAR WARS
2,Star Wars : Episodio VI - El retorno del Jedi,1983,"32,500,000",32.5,30.0625,475.106177,439.473214,STAR WARS
3,Star Wars: Episodio I - La Amenaza fantasma,1999,"115,000,000",115.0,106.3750,1027.082707,950.051504,STAR WARS
4,Star Wars: Episodio II - El ataque de los clones,2002,"115,000,000",115.0,106.3750,653.779970,604.746472,STAR WARS
5,Star Wars: Episodio III - La venganza de los Sith,2005,"113,000,000",113.0,104.5250,868.390560,803.261268,STAR WARS
6,The Avengers,2012,"220,000,000",220.0,203.5000,15188.115515,14049.006851,AVENGERS
7,Star Wars : Episodio VII - El despertar de la...,2015,"245,000,000",245.0,226.6250,2069.521700,1914.307572,STAR WARS
8,The Avengers: Age of Ultron,2015,"250,000,000",250.0,231.2500,1402.809540,1297.598824,AVENGERS
9,Star Wars : Episodio VIII - Los últimos Jedi,2017,"317,000,000",317.0,293.2250,1332.698830,1232.746418,STAR WARS
10,The Avengers: Infinity War,2018,"316,000,000",316.0,292.3000,2048.359754,1894.732772,AVENGERS
11,Star Wars: Episodio IX -El ascenso de Skywalker,2019,"275,000,000",275.0,254.3750,1078.232589,997.365145,STAR WARS
12,The Avengers: Endgame,2019,"356,000,000",356.0,329.3000,2797.501328,2587.688728,AVENGERS

In [20]:
raw_data=raw_data[['PELICULA','SAGA', 'ESTRENO', 'PRESUPUESTO',
       'PRESUPUESTO (millones de dólares)',
       'PRESUPUESTO PONDERADO POR INFLACION',
       'RECAUDACION (millones de dolares)',
       'RECAUDACION PONDERADA POR INFLACION',]]

In [21]:
raw_data

,PELICULA,SAGA,ESTRENO,PRESUPUESTO,PRESUPUESTO (millones de dólares),PRESUPUESTO PONDERADO POR INFLACION,RECAUDACION (millones de dolares),RECAUDACION PONDERADA POR INFLACION
0,Star Wars : Episodio IV - Una nueva esperanza,STAR WARS,1977,"11,000,000",11.0,10.1750,775.398007,717.243156
1,Star Wars: Episodio V - EL imperio contraataca,STAR WARS,1980,"18,000,000",18.0,16.6500,538.375067,497.996937
2,Star Wars : Episodio VI - El retorno del Jedi,STAR WARS,1983,"32,500,000",32.5,30.0625,475.106177,439.473214
3,Star Wars: Episodio I - La Amenaza fantasma,STAR WARS,1999,"115,000,000",115.0,106.3750,1027.082707,950.051504
4,Star Wars: Episodio II - El ataque de los clones,STAR WARS,2002,"115,000,000",115.0,106.3750,653.779970,604.746472
5,Star Wars: Episodio III - La venganza de los Sith,STAR WARS,2005,"113,000,000",113.0,104.5250,868.390560,803.261268
6,The Avengers,AVENGERS,2012,"220,000,000",220.0,203.5000,15188.115515,14049.006851
7,Star Wars : Episodio VII - El despertar de la...,STAR WARS,2015,"245,000,000",245.0,226.6250,2069.521700,1914.307572
8,The Avengers: Age of Ultron,AVENGERS,2015,"250,000,000",250.0,231.2500,1402.809540,1297.598824
9,Star Wars : Episodio VIII - Los últimos Jedi,STAR WARS,2017,"317,000,000",317.0,293.2250,1332.698830,1232.746418
10,The Avengers: Infinity War,AVENGERS,2018,"316,000,000",316.0,292.3000,2048.359754,1894.732772
11,Star Wars: Episodio IX -El ascenso de Skywalker,STAR WARS,2019,"275,000,000",275.0,254.3750,1078.232589,997.365145
12,The Avengers: Endgame,AVENGERS,2019,"356,000,000",356.0,329.3000,2797.501328,2587.688728

Aunque podríamos empezar ya comparando recaudaciones, me gustaría obtener una columna beneficios donde reflejaría los beneficios como la diferencia entre el presupuesto(lo que costó la película) y la recaudacion y otra columna que reflejaría el beneficio relativo en tanto por ciento ya que puede darse el caso de que una película/saga tenga una recaudación mayor, pero también es posible que haya un mayor presupuesto.

In [22]:
raw_data['BENEFICIO NETO']=raw_data['RECAUDACION PONDERADA POR INFLACION']-raw_data['PRESUPUESTO PONDERADO POR INFLACION']
raw_data

C:\Users\dalcaraz.ferri\AppData\Local\Temp\ipykernel_26104\1802942660.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_data['BENEFICIO NETO']=raw_data['RECAUDACION PONDERADA POR INFLACION']-raw_data['PRESUPUESTO PONDERADO POR INFLACION']

,PELICULA,SAGA,ESTRENO,PRESUPUESTO,PRESUPUESTO (millones de dólares),PRESUPUESTO PONDERADO POR INFLACION,RECAUDACION (millones de dolares),RECAUDACION PONDERADA POR INFLACION,BENEFICIO NETO
0,Star Wars : Episodio IV - Una nueva esperanza,STAR WARS,1977,"11,000,000",11.0,10.1750,775.398007,717.243156,707.068156
1,Star Wars: Episodio V - EL imperio contraataca,STAR WARS,1980,"18,000,000",18.0,16.6500,538.375067,497.996937,481.346937
2,Star Wars : Episodio VI - El retorno del Jedi,STAR WARS,1983,"32,500,000",32.5,30.0625,475.106177,439.473214,409.410714
3,Star Wars: Episodio I - La Amenaza fantasma,STAR WARS,1999,"115,000,000",115.0,106.3750,1027.082707,950.051504,843.676504
4,Star Wars: Episodio II - El ataque de los clones,STAR WARS,2002,"115,000,000",115.0,106.3750,653.779970,604.746472,498.371472
5,Star Wars: Episodio III - La venganza de los Sith,STAR WARS,2005,"113,000,000",113.0,104.5250,868.390560,803.261268,698.736268
6,The Avengers,AVENGERS,2012,"220,000,000",220.0,203.5000,15188.115515,14049.006851,13845.506851
7,Star Wars : Episodio VII - El despertar de la...,STAR WARS,2015,"245,000,000",245.0,226.6250,2069.521700,1914.307572,1687.682572
8,The Avengers: Age of Ultron,AVENGERS,2015,"250,000,000",250.0,231.2500,1402.809540,1297.598824,1066.348824
9,Star Wars : Episodio VIII - Los últimos Jedi,STAR WARS,2017,"317,000,000",317.0,293.2250,1332.698830,1232.746418,939.521418
10,The Avengers: Infinity War,AVENGERS,2018,"316,000,000",316.0,292.3000,2048.359754,1894.732772,1602.432772
11,Star Wars: Episodio IX -El ascenso de Skywalker,STAR WARS,2019,"275,000,000",275.0,254.3750,1078.232589,997.365145,742.990145
12,The Avengers: Endgame,AVENGERS,2019,"356,000,000",356.0,329.3000,2797.501328,2587.688728,2258.388728

In [23]:
raw_data['BENEFICIO RELATIVO %']=(raw_data['BENEFICIO NETO']/raw_data['RECAUDACION PONDERADA POR INFLACION'])*100
raw_data

C:\Users\dalcaraz.ferri\AppData\Local\Temp\ipykernel_26104\1212653093.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_data['BENEFICIO RELATIVO %']=(raw_data['BENEFICIO NETO']/raw_data['RECAUDACION PONDERADA POR INFLACION'])*100

,PELICULA,SAGA,ESTRENO,PRESUPUESTO,PRESUPUESTO (millones de dólares),PRESUPUESTO PONDERADO POR INFLACION,RECAUDACION (millones de dolares),RECAUDACION PONDERADA POR INFLACION,BENEFICIO NETO,BENEFICIO RELATIVO %
0,Star Wars : Episodio IV - Una nueva esperanza,STAR WARS,1977,"11,000,000",11.0,10.1750,775.398007,717.243156,707.068156,98.581374
1,Star Wars: Episodio V - EL imperio contraataca,STAR WARS,1980,"18,000,000",18.0,16.6500,538.375067,497.996937,481.346937,96.656606
2,Star Wars : Episodio VI - El retorno del Jedi,STAR WARS,1983,"32,500,000",32.5,30.0625,475.106177,439.473214,409.410714,93.159424
3,Star Wars: Episodio I - La Amenaza fantasma,STAR WARS,1999,"115,000,000",115.0,106.3750,1027.082707,950.051504,843.676504,88.803239
4,Star Wars: Episodio II - El ataque de los clones,STAR WARS,2002,"115,000,000",115.0,106.3750,653.779970,604.746472,498.371472,82.409984
5,Star Wars: Episodio III - La venganza de los Sith,STAR WARS,2005,"113,000,000",113.0,104.5250,868.390560,803.261268,698.736268,86.987422
6,The Avengers,AVENGERS,2012,"220,000,000",220.0,203.5000,15188.115515,14049.006851,13845.506851,98.551499
7,Star Wars : Episodio VII - El despertar de la...,STAR WARS,2015,"245,000,000",245.0,226.6250,2069.521700,1914.307572,1687.682572,88.161516
8,The Avengers: Age of Ultron,AVENGERS,2015,"250,000,000",250.0,231.2500,1402.809540,1297.598824,1066.348824,82.178621
9,Star Wars : Episodio VIII - Los últimos Jedi,STAR WARS,2017,"317,000,000",317.0,293.2250,1332.698830,1232.746418,939.521418,76.213681
10,The Avengers: Infinity War,AVENGERS,2018,"316,000,000",316.0,292.3000,2048.359754,1894.732772,1602.432772,84.573022
11,Star Wars: Episodio IX -El ascenso de Skywalker,STAR WARS,2019,"275,000,000",275.0,254.3750,1078.232589,997.365145,742.990145,74.495299
12,The Avengers: Endgame,AVENGERS,2019,"356,000,000",356.0,329.3000,2797.501328,2587.688728,2258.388728,87.274358

Parece que habríamos terminado de limpiar la tabla; en un primer vistazo vemos que hay 2 películas de la Saga Vengadores que coinciden en el año de estreno. Será intersante poner cierto foco en este suceso, ya que considero que no es lo mismo que en el mismo año se tenga la opción de ver una u otra pelicula, que solamente de tener una opción. En el año 2019 "Endgame" y "el ascenso de Skywalker" se estrenaron, y la diferencia de ganancias entre estos dos cierres de saga es más que edvidente con un 87% de beneficio neto para la saga de los superhéroes frente a un modesto 74% para la saga de los jedis.

# ANÁLISIS DESCRIPTIVO

## PELICULAS CON MAYOR PRESUPUESTO

In [24]:
import altair as alt

In [25]:
raw_data

,PELICULA,SAGA,ESTRENO,PRESUPUESTO,PRESUPUESTO (millones de dólares),PRESUPUESTO PONDERADO POR INFLACION,RECAUDACION (millones de dolares),RECAUDACION PONDERADA POR INFLACION,BENEFICIO NETO,BENEFICIO RELATIVO %
0,Star Wars : Episodio IV - Una nueva esperanza,STAR WARS,1977,"11,000,000",11.0,10.1750,775.398007,717.243156,707.068156,98.581374
1,Star Wars: Episodio V - EL imperio contraataca,STAR WARS,1980,"18,000,000",18.0,16.6500,538.375067,497.996937,481.346937,96.656606
2,Star Wars : Episodio VI - El retorno del Jedi,STAR WARS,1983,"32,500,000",32.5,30.0625,475.106177,439.473214,409.410714,93.159424
3,Star Wars: Episodio I - La Amenaza fantasma,STAR WARS,1999,"115,000,000",115.0,106.3750,1027.082707,950.051504,843.676504,88.803239
4,Star Wars: Episodio II - El ataque de los clones,STAR WARS,2002,"115,000,000",115.0,106.3750,653.779970,604.746472,498.371472,82.409984
5,Star Wars: Episodio III - La venganza de los Sith,STAR WARS,2005,"113,000,000",113.0,104.5250,868.390560,803.261268,698.736268,86.987422
6,The Avengers,AVENGERS,2012,"220,000,000",220.0,203.5000,15188.115515,14049.006851,13845.506851,98.551499
7,Star Wars : Episodio VII - El despertar de la...,STAR WARS,2015,"245,000,000",245.0,226.6250,2069.521700,1914.307572,1687.682572,88.161516
8,The Avengers: Age of Ultron,AVENGERS,2015,"250,000,000",250.0,231.2500,1402.809540,1297.598824,1066.348824,82.178621
9,Star Wars : Episodio VIII - Los últimos Jedi,STAR WARS,2017,"317,000,000",317.0,293.2250,1332.698830,1232.746418,939.521418,76.213681
10,The Avengers: Infinity War,AVENGERS,2018,"316,000,000",316.0,292.3000,2048.359754,1894.732772,1602.432772,84.573022
11,Star Wars: Episodio IX -El ascenso de Skywalker,STAR WARS,2019,"275,000,000",275.0,254.3750,1078.232589,997.365145,742.990145,74.495299
12,The Avengers: Endgame,AVENGERS,2019,"356,000,000",356.0,329.3000,2797.501328,2587.688728,2258.388728,87.274358

In [26]:
raw_data.groupby(['SAGA']).mean()['PRESUPUESTO PONDERADO POR INFLACION']

SAGA
AVENGERS     264.087500
STAR WARS    127.598611
Name: PRESUPUESTO PONDERADO POR INFLACION, dtype: float64